import { StatusBar } from 'expo-status-bar';
import { SafeAreaView , ScrollView,  Keyboard, TouchableWithoutFeedback, Platform, StyleSheet, Text, View , Image, Dimensions, TextInput , KeyboardAvoidingView} from 'react-native';
import React, { Children } from 'react'
//import { Box, Input } from 'native-base'

const win = Dimensions.get('window')

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#3C8547',
        alignItems: 'center',
        paddingHorizontal: 0,
        justifyContent: 'center',
        position: 'relative',
        resizeMode: 'contain'
    },
    containner2: {
        flex: 1,
        backgroundColor: 'transparent',
        position: 'absolute',
        paddingHorizontal: 0,
        top: 0,
        alignSelf: 'center',
        height: win.height,
        
        //justifyContent: 'center',
    },
    scrollview: {
        marginHorizontal: 20,
        top: 200,
        position: "absolute",
    },
    TitleText: {
        flex: 1,
        fontSize: 60,
        fontFamily: "normal",
        alignSelf: 'center',
        color: 'white',
        top: 20,
    },  
    icon: {
        alignSelf: 'center',
        top: 160,
        objectFit: "cover",
        position: "absolute",
      //justifycontent: "flex-start",
      
    },
    icon2: {
        alignSelf: 'center',
        top: 100,
        objectFit: "cover",
        position: "absolute",
        resizeMode: 'center',
        width: 640,
        height: 640,
    },
    icon3: {
        alignSelf: 'center',
        top: 250,
        objectFit: "cover",
        position: "absolute",
        resizeMode: 'center',
        width: 420,
        height: 420,
    },
    inputUsername: {
        top: 80,
        margin: 20,
        borderWidth: 1,
        padding: 10,
        position: "relative",
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 55,   
        width: 240,   
        alignSelf: 'center',
        height: 50
    },
    inputEmail: {
        top: 20 + 120,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        position: "absolute",
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 55,   
        width: 240,   
        alignSelf: 'center'
    },
    inputPass: {
        top: 30 ,
        margin: 40,
        borderWidth: 1,
        padding: 10,
        position: "relative",
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 50,    
        width: 240, 
        alignSelf: 'center'
    },
    input2: {
        height: 40,
        margin: 12,
        borderWidth: 1,
        padding: 10,   
    },
    buttonEntry: {
        top: 520,
        width: 100,
        height: 6*win.height/8,
        left: 200,
        position: 'absolute',
    },
    buttonInsert: {
        top: 520,
        width: 100,
        height: 6*win.height/8,
        left: 60,
        position: 'absolute',
    },
    userLoc: {
        position: 'absolute',
        top: 0,
        left: 0,
    },
    upperbar: {
        top: 0,
        left: 0,
        position: 'absolute',
        color: 'green',
        backgroundColor: 'white',
        borderBlockColor: 'black',
        borderRadius: 5,
        width: win.width,
        height: 80,
        
    },
    homeIcon: {
        position: 'absolute',
        alignSelf: 'center',
        top: 25,
    },
    homeIcon2: {
        resizeMode: 'contain',
        width: 35,
        height: 35,
    },
    optIcon: {
        position: 'absolute',
        top: 25,
        left: win.width - 45,
    },
    optIcon2:{
        resizeMode: 'contain',
        height: 30,
        width: 30,
    },
    photoIcon: {
        position: 'absolute',
        top: 180,
        left:  2.2*win.width/10 -126.4/2,
    },
    ListIcon: {
        position: 'absolute',
        top: 180 + 20,
        left: 7*win.width/10 -126.4/2,
        
    },
    DoencaIcon: {
        position: 'absolute',
        top: 180 + 20 + 180,
        left: 7*win.width/10 -126.4/2,
    },
    textPhoto1: {
        alignSelf: 'center',
        top: 120,
        position: 'absolute',
    },
    selecPlant: {
        position: 'absolute',
        top: 270,
        resizeMode: 'center',
        width: 250,
        height: 300,
        paddingTop: 20,
        borderEndColor: '#16441D',
        borderRadius: 100,
    },
    listingBackground: {
        color: 'white',
        width: win.width/1.1,
        height: 600,
        alignSelf: 'center',
        position: 'absolute',
        top: 120,
        fontSize: 50,
        backgroundColor: 'white',
        borderTopLeftRadius: 10,
        borderTopRightRadius: 10
    },
    registerField: {
        top: 0,
        margin: 8,
        borderWidth: 1,
        padding: 10,
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 50,    
        width: 240, 
        alignSelf: 'center',
    },
    registerEmail: {
        top: 0,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 50,    
        width: 240, 
        alignSelf: 'center',
    },
    registerPass: {
        top: 0,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 50,    
        width: 240, 
        alignSelf: 'center',
    },
    registerName: {
        top: 0,
        margin: 12,
        borderWidth: 1,
        padding: 10,
        color: 'black',
        backgroundColor: 'white',
        borderColor: "white",
        borderRadius: 50,    
        width: 240, 
        alignSelf: 'center',
    }
})